# Case Study

To illustrate some of these ideas we can use a case study of influenza in a boarding school (1978). These data are from a paper in the BMJ in 1978[^1] and provided at [http://kingaa.github.io/short-course/stochsim/bsflu_data.txt](http://kingaa.github.io/short-course/stochsim/bsflu_data.txt). I have downloaded the file as "BS.csv".

[^1]: Influenza in a Boarding School. British Medical Journal, **1:587**, 1978.

The event probabilities are:

\begin{align*}
    P\left[\mbox{infection ($I$) event in}~[t, t + \delta t)\right] &= \beta S I / N + o(\delta t)\\
    P\left[\mbox{bed-rest ($B$) event in}~[t, t + \delta t)\right] &= \mu_I I + o(\delta t)\\
    P\left[\mbox{convalescence ($C$) event in}~[t, t + \delta t)\right] &= \mu_B B + o(\delta t)
\end{align*}

Here we are going to match to the final epidemic size (512 children), and the sum-of-squared differences between the observed bed-rest counts (given by `BS$B`) and the simulated bed-rest counts (given by the $B$ class in our model). The initial population size is 763 pupils, and we assume an initial introduction of infection of a single boy at day 0.

```{r, case-BS, message = F, warning = F}
## load data
BS <- read.csv("BS.csv", header = T)

## plot data
ylims <- c(0, max(c(BS$B, BS$C)))
plot(BS$day, BS$B, xlab = "Day", ylab = "Count", ylim = ylims, type = "l")
lines(BS$day, BS$C, col = "blue")
legend(11, 290, legend = c("B", "C"), col = c("black", "blue"), lty = 1)
```
