--- 
title: "Inference in infectious disease systems practicals"
author: "TJ McKinley"
site: bookdown::bookdown_site
output:
    bookdown::pdf_book:
        includes:
            in_header: header.tex
    bookdown::gitbook:
        config:
            sharing: null
        css: 'style.css'
        includes:
            in_header: _toggle.html
        keep_md: TRUE
linkcolor: blue
documentclass: book
bibliography: ref.bib
link-citations: yes
description: "Inference in infectious disease systems practicals"
---

# Introduction

```{r, setup, child = "_setup.Rmd", include = F, purl = F, cache = F}
```

The purpose of this document is to run some ABC-SMC routines using the (current) `SimBIID` package (Simulation-Based Inference for Infectious Disease models). I am heavily indebted to Stefan Widgren for his fantastic [SimInf](https://cran.r-project.org/web/packages/SimInf/index.html) package, and indeed I shamelessly borrow some of his ideas (such as the `mparse()` function).

In the longer term, it would be good to have a fully `SimInf` supported version of this package, but for the time being I have developed `SimBIID` mostly as a tool to help you learn how ABC-SMC (and other routines) work, and to allow you to get your hands dirty with some real models/data, but without the complexities of having to code these routines up yourselves.

[As an aside, the [pomp](https://kingaa.github.io/pomp/) package does this to a certain extent, but the interface is more complex, and the package does not implement all of the types of routine that I would like to use (such as the alive particle filter based PMCMC, or the commonly employed ABC-SMC routine of Toni et al., 2009). However, it is powerful and flexible, so please check this out also.]

The workhorse of `SimBIID` is the function `mparseRcpp()`, which apes the syntax of `mparse()`, but allows for different output options. It does not have the full power of `SimInf`, so currently only works on single node simulations (no networks), with some limited additional structures. It also implements a simple Gillespie algorithm, rather than the more sophisticated approaches used in `SimInf` and `pomp`, but it's fast enough for the examples here. It also allows for other things such as the inclusion of early stopping criteria, which often greatly help to improve efficiency in say ABC-SMC routines (particularly in poorly supported regions of the parameter space).

